// Simple 3-letter words appropriate for young readers
export const WORDS = [
  "ant","ape","arm","art","ash","axe",
  "bad","bag","ban","bat","bay","bed","big","bit","bud","bug","bun","bus","but",
  "cab","can","cap","cat","cod","cog","cop","cub","cup","cut",
  "dab","dam","dig","dim","dip","dog","dot","dug","dun",
  "egg","elf","elm","end","eve",
  "fan","fat","fed","fig","fit","fix","fog","fun",
  "gab","gal","gap","gas","get","got","gum","gun","gut",
  "had","ham","hat","hay","hen","him","hip","hit","hop","hot","hub","hug","hum","hut",
  "ill","ink",
  "jam","jar","jet","jig","job","jog","jot","joy","jug","jut",
  "keg","kin","kit",
  "lad","lag","lap","law","lay","led","leg","let","lid","lip","lit","log","lot","lug",
  "mad","man","map","mat","men","mob","mop","mud","mug",
  "nab","nag","nap","net","nip","nod","nut",
  "old","ore","owl","own",
  "pad","pan","pat","paw","peg","pet","pig","pin","pit","pod","pop","pot","pub","pun","put",
  "rag","ram","ran","rap","rat","ray","red","rib","rim","rip","rob","rod","rot","row","rub","rug","run","rut",
  "sag","sap","sat","saw","set","sip","sit","six","sob","sod","son","sub","sum","sun",
  "tab","tan","tap","tar","tin","tip","top","tub","tug",
  "van","vet",
  "war","wax","web","wet","wig","win","wit",
  "yam","yap","yew",
  "zap","zip",
];
